export const products = [
     {
         productId: 1,
         productName: "Liten sushi 8 bitar",
         productDescription: "3 lax, 1 räka, 1 avokado, 3 futomakirullar med chilimajonnäs, ål sås, sesamfrö, rom och rostad lök.",
         productImage: "/images/products/Liten sushi 8 bitar.jpg",
         productPrice: 110,
      },
     {
        productId: 2,
        productName: "Mellan sushi 11 bitar",
        productDescription: "3 lax, 1 räka, 1 avokado, 1 tonfisk, 1 bläckfisk, 4 futomakirullar med chilimajonnäs, ål sås, sesamfrö, rom och rostad lök.",
        productImage: "/images/products/Mellan sushi 11 bitar.jpg",
        productPrice: 145,
     },
     {
       productId: 3,
       productName: "Stor sushi 14 bitar",
       productDescription: "5 lax, 1 räka, 1 avokado, 1 tonfisk, 1 hokkigai mussla, 1 bläckfisk, 4 futomakirullar med chilimajonnäs, ål sås, sesamfrö, rom och rostad lök.",
       productImage: "/images/products/Stor sushi 14 bitar.jpg",
       productPrice: 165,
    },
    {
      productId: 4,
      productName: "Lätt grillad 8 bitar",
      productDescription: "Halstrad lax med chilimajonnäs, ålsås, sesamfrö och rostad lök.",
      productImage: "/images/products/Lätt grillad 8 bitar.jpg",
      productPrice: 150,
   },
   {
      productId: 5,
      productName: "Yume special sushi 11 bitar",
      productDescription: "3 lax, 1 räka, 1 avokado, 1 tonfisk, 1 hokkigai mussla, 1 pilgrims mussla, 1 sardin, 1 ål, 1 bläckfisk, chillimajonäs, ålsås, sesamfrö, rom och rostad lök.",
      productImage: "/images/products/Yume special sushi 11 bitar.jpg",
      productPrice: 165,
   },
   {
      productId: 6,
      productName: "Lax sushi 9 bitar",
      productDescription: "9 bitar laxnigiri med chilimajonnäs, ål sås, sesamfrö, rom och rostad lök.",
      productImage: "/images/products/Lax sushi 9 bitar.jpg",
      productPrice: 150,
   },
   {
      productId: 7,
      productName: "Lax avokado sushi 9 bitar",
      productDescription: "5 lax, 4 avokado, chilimajonnäs, ål sås, sesamfrö, rom och rostad lök.",
      productImage: "/images/products/Lax avokado sushi 9 bitar.jpg",
      productPrice: 145,
   },
   {
      productId: 8,
      productName: "Lax räkor sushi 9 bitar",
      productDescription: "5 lax, 4 räkor, chilimajonnäs, ål sås, sesamfrö, rom och rostad lök.",
      productImage: "/images/products/Lax räkor sushi 9 bitar.jpg",
      productPrice: 145,
   },
   {
      productId: 9,
      productName: "Räk sushi 9 bitar",
      productDescription: "9 bitar räknigiri med chilimajonnäs, ål sås, sesamfrö, rom och rostad lök.",
      productImage: "/images/products/Räk sushi 9 bitar.jpg",
      productPrice: 145,
    },
   {
      productId: 10,
      productName: "Vegetarisk sushi 9 bitar",
      productDescription: "3 avokado, 2 tofu, 4 vegetariska rullar, edamame, soya sås, sesamfrö och rostad lök.",
      productImage: "/images/products/Vegetarisk sushi 9 bitar.jpg",
      productPrice: 120,
   },
   {
      productId: 11,
      productName: "Vegetarisk sushi 12 bitar",
      productDescription: "5 avokado, 3 tofu, 4 vegetariska rullar, edamame, soya sås, sesamfrö och rostad lök.",
      productImage: "/images/products/Vegetarisk sushi 12 bitar.jpg",
      productPrice: 140,
   },
   {
      productId: 12,
      productName: "Mamma sushi 9 bitar",
      productDescription: "2 avokado, 1 räka, 1 tofu, 1 crabstick surimi, 4 vegetariska rullar, chilimajonnäs, soya sås, sesamfrö och rostad lök.",
      productImage: "/images/products/Mamma sushi 9 bitar.jpg",
      productPrice: 120,
   },
   {
      productId: 13,
      productName: "Mamma sushi 12 bitar",
      productDescription: "4 avokado, 1 räka, 2 tofu, 1 crabstick surimi, 4 vegetariska rullar, chilimajonnäs, soya sås, sesamfrö och rostad lök.",
      productImage: "/images/products/Mamma sushi 12 bitar.jpg",
      productPrice: 140,
   },
   {
      productId: 14,
      productName: "Sashimi mellan",
      productDescription: "Olika sorters rå fisk med blandad sallad, chilimajonnäs, ål sås, sesamfrö och rostad lök",
      productImage: "/images/products/Sashimi mellan.jpg",
      productPrice: 205,
   },
   {
      productId: 15,
      productName: "Sushi 6 bitar och sashimi",
      productDescription: "Olika sorters rå fisk med blandad sallad, chilimajonnäs, ål sås, sesamfrö, rom och rostad lök.",
      productImage: "/images/products/Sushi 6 bitar och sashimi.jpg",
      productPrice: 250,
   },
   {
      productId: 16,
      productName: "Yume special roll 10 bitar",
      productDescription: "Lax, tonfisk, avokado, gurka, crabstick surimi, ål sås, chilimajonnäs, sesamfrö och rostad lök.",
      productImage: "/images/products/Yume special roll 10 bitar.jpg",
      productPrice: 165,
   },
]